project:
  type: website
  output-dir: docs
  
website:
  title: "Justine Shakespeare"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About"
      - Projects.qmd
      - href: ProfessionalWork.qmd
        text: Professional Work
      - href: JS_Resume.qmd
        text: Resume
        
      
# (this is where you put the different links on the nav bar)

format:
  html:
    theme: 
      - yeti #(lumen, yeti, minty)
      - custom.scss
    backgroundcolor: "#ECEBE4" # (SEASALT:#FAF9F9, Alabaster: #ECEBE4)
    #css: styles.css
    toc: true


    #mainfont: "Arial"
    fontsize: 1.1rem
    linkcolor: "#0075C4" # (French blue: #0075C4, nice blue: 2D93AD)

# (For more options: https://quarto.org/docs/output-formats/html-themes.html)

editor: visual

